wandb_version: 1

model:
  desc: null
  value: U_Net
dataset:
  desc: null
  value: ptb
epochs:
  desc: null
  value: 1000
loss:
  desc: null
  value: BCE
lr:
  desc: null
  value: 1.0e-05
optimizer:
  desc: null
  value: SGD
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686495853.902439
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 5
